import dlt
from dlt.sources.helpers import requests


@dlt.source()
def types_source():

    return types_resource()


@dlt.resource(write_disposition="append")
def types_resource():
    mapping_list = [
        ("schema:House", "Accommodation & Lodging"),
        ("AccommodationProduct", "Accommodation & Lodging"),
        ("Accommodation", "Accommodation & Lodging"),
        ("StopOverOrGroupLodge", "Accommodation & Lodging"),
        ("Camping", "Accommodation & Lodging"),
        ("HouseBoat", "Accommodation & Lodging"),
        ("schema:BedAndBreakfast", "Accommodation & Lodging"),
        ("CamperVanArea", "Accommodation & Lodging"),
        ("schema:LodgingBusiness", "Accommodation & Lodging"),
        ("House", "Accommodation & Lodging"),
        ("CampingAndCaravanning", "Accommodation & Lodging"),
        ("Guesthouse", "Accommodation & Lodging"),
        ("schema:Accommodation", "Accommodation & Lodging"),
        ("RentalAccommodation", "Accommodation & Lodging"),
        ("CollectiveAccommodation", "Accommodation & Lodging"),
        ("GroupLodging", "Accommodation & Lodging"),
        ("FarmhouseInn", "Accommodation & Lodging"),
        ("MountainResort", "Accommodation & Lodging"),
        ("ServiceProvider", "Business Centers & Services"),
        ("schema:LocalBusiness", "Business Centers & Services"),
        ("ConvenientService", "Business Centers & Services"),
        ("ConventionCentre", "Business Centers & Services"),
        ("Trader", "Business Centers & Services"),
        ("ProducersGroup", "Business Centers & Services"),
        ("IndustrialSite", "Business Centers & Services"),
        ("BusinessPlace", "Business Centers & Services"),
        ("MultiPurposeRoomOrCommunityRoom", "Business Centers & Services"),
        ("schema:TouristInformationCenter", "Business Centers & Services"),
        ("Cybercafe", "Business Centers & Services"),
        ("Conference", "Business Centers & Services"),
        ("NonHousingRealEstateRental", "Business Centers & Services"),
        ("EquipmentRentalShop", "Business Centers & Services"),
        ("WifiHotSpot", "Business Centers & Services"),
        ("Cooperative", "Business Centers & Services"),
        ("Producer", "Business Centers & Services"),
        ("EquipmentRental", "Business Centers & Services"),
        ("schema:Museum", "Cultural Centers & Museums"),
        ("Museum", "Cultural Centers & Museums"),
        ("Library", "Cultural Centers & Museums"),
        ("InterpretationCentre", "Cultural Centers & Museums"),
        ("schema:Library", "Cultural Centers & Museums"),
        ("ArtGalleryOrExhibitionGallery", "Cultural Centers & Museums"),
        ("CulturalSite", "Cultural Centers & Museums"),
        ("schema:ExhibitionEvent", "Cultural/Social Events"),
        ("SaleEvent", "Cultural/Social Events"),
        ("ShowEvent", "Cultural/Social Events"),
        ("schema:Festival", "Cultural/Social Events"),
        ("BusinessEvent", "Cultural/Social Events"),
        ("schema:SaleEvent", "Cultural/Social Events"),
        ("SocialEvent", "Cultural/Social Events"),
        ("CulturalEvent", "Cultural/Social Events"),
        ("Carnival", "Cultural/Social Events"),
        ("Exhibition", "Cultural/Social Events"),
        ("schema:Event", "Cultural/Social Events"),
        ("Festival", "Cultural/Social Events"),
        ("ChildrensEvent", "Cultural/Social Events"),
        ("schema:BusinessEvent", "Cultural/Social Events"),
        ("EducationalTrail", "Educational Centers"),
        ("IntroductionCourse", "Educational Centers"),
        ("Traineeship", "Educational Centers"),
        ("DevelopmentCourse", "Educational Centers"),
        ("TeachingFarm", "Educational Centers"),
        ("ActivityProvider", "Entertainment & Leisure"),
        ("schema:MovieTheater", "Entertainment & Leisure"),
        ("Cirque", "Entertainment & Leisure"),
        ("schema:Casino", "Entertainment & Leisure"),
        ("YachtClub", "Entertainment & Leisure"),
        ("Cinematheque", "Entertainment & Leisure"),
        ("Auditorium", "Entertainment & Leisure"),
        ("Arena", "Entertainment & Leisure"),
        ("ZooAnimalPark", "Entertainment & Leisure"),
        ("KidsClub", "Entertainment & Leisure"),
        ("Theater", "Entertainment & Leisure"),
        ("Casino", "Entertainment & Leisure"),
        ("CircusPlace", "Entertainment & Leisure"),
        ("CulturalActivityProvider", "Entertainment & Leisure"),
        ("EntertainmentAndEvent", "Entertainment & Leisure"),
        ("PlayArea", "Entertainment & Leisure"),
        ("ThemePark", "Entertainment & Leisure"),
        ("schema:AmusementPark", "Entertainment & Leisure"),
        ("schema:MusicEvent", "Entertainment & Leisure"),
        ("NightClub", "Entertainment & Leisure"),
        ("schema:Aquarium", "Entertainment & Leisure"),
        ("FairOrShow", "Entertainment & Leisure"),
        ("schema:NightClub", "Entertainment & Leisure"),
        ("Cinema", "Entertainment & Leisure"),
        ("VivariumAquarium", "Entertainment & Leisure"),
        ("BilliardRoom", "Entertainment & Leisure"),
        ("schema:TheaterEvent", "Entertainment & Leisure"),
        ("Cabaret", "Entertainment & Leisure"),
        ("schema:Zoo", "Entertainment & Leisure"),
        ("Concert", "Entertainment & Leisure"),
        ("Game", "Entertainment & Leisure"),
        ("BeachClub", "Entertainment & Leisure"),
        ("schema:Restaurant", "Food & Dining"),
        ("FoodEstablishment", "Food & Dining"),
        ("FastFoodRestaurant", "Food & Dining"),
        ("BarOrPub", "Food & Dining"),
        ("IceCreamShop", "Food & Dining"),
        ("CafeOrTeahouse", "Food & Dining"),
        ("Tasting", "Food & Dining"),
        ("schema:IceCreamShop", "Food & Dining"),
        ("schema:CafeOrCoffeeShop", "Food & Dining"),
        ("WineCellar", "Food & Dining"),
        ("Brewery", "Food & Dining"),
        ("TastingProvider", "Food & Dining"),
        ("Tower", "Historical/Cultural Sites"),
        ("Citadel", "Historical/Cultural Sites"),
        ("RemarkableHouse", "Historical/Cultural Sites"),
        ("Dungeon", "Historical/Cultural Sites"),
        ("Fort", "Historical/Cultural Sites"),
        ("Lighthouse", "Historical/Cultural Sites"),
        ("TriumphalArch", "Historical/Cultural Sites"),
        ("Aqueduct", "Historical/Cultural Sites"),
        ("TechnicalHeritage", "Historical/Cultural Sites"),
        ("RemarkableBuilding", "Historical/Cultural Sites"),
        ("Fountain", "Historical/Cultural Sites"),
        ("MegalithDolmenMenhir", "Historical/Cultural Sites"),
        ("Chartreuse", "Historical/Cultural Sites"),
        ("Ruins", "Historical/Cultural Sites"),
        ("CityHeritage", "Historical/Cultural Sites"),
        ("FortifiedSet", "Historical/Cultural Sites"),
        ("Bastide", "Historical/Cultural Sites"),
        ("RemembranceSite", "Historical/Cultural Sites"),
        ("DefenceSite", "Historical/Cultural Sites"),
        ("FortifiedCastle", "Historical/Cultural Sites"),
        ("MilitaryCemetery", "Historical/Cultural Sites"),
        ("ArcheologicalSite", "Historical/Cultural Sites"),
        ("schema:CivicStructure", "Historical/Cultural Sites"),
        ("Mill", "Historical/Cultural Sites"),
        ("Palace", "Historical/Cultural Sites"),
        ("Castle", "Historical/Cultural Sites"),
        ("WashHouse", "Historical/Cultural Sites"),
        ("schema:Park", "Outdoor/Natural Attractions"),
        ("ParkAndGarden", "Outdoor/Natural Attractions"),
        ("Farmer", "Outdoor/Natural Attractions"),
        ("Coastline", "Outdoor/Natural Attractions"),
        ("CaveSinkholeOrAven", "Outdoor/Natural Attractions"),
        ("Peak", "Outdoor/Natural Attractions"),
        ("Bog", "Outdoor/Natural Attractions"),
        ("Glacier", "Outdoor/Natural Attractions"),
        ("HalophilicArea", "Outdoor/Natural Attractions"),
        ("Rambling", "Outdoor/Natural Attractions"),
        ("schema:Landform", "Outdoor/Natural Attractions"),
        ("Farm", "Outdoor/Natural Attractions"),
        ("Gorge", "Outdoor/Natural Attractions"),
        ("River", "Outdoor/Natural Attractions"),
        ("Forest", "Outdoor/Natural Attractions"),
        ("PointOfView", "Outdoor/Natural Attractions"),
        ("Bocage", "Outdoor/Natural Attractions"),
        ("Plateau", "Outdoor/Natural Attractions"),
        ("Grassland", "Outdoor/Natural Attractions"),
        ("CyclingTour", "Outdoor/Natural Attractions"),
        ("Swamp", "Outdoor/Natural Attractions"),
        ("Pond", "Outdoor/Natural Attractions"),
        ("Source", "Outdoor/Natural Attractions"),
        ("Lock", "Outdoor/Natural Attractions"),
        ("Crest", "Outdoor/Natural Attractions"),
        ("ConeNeck", "Outdoor/Natural Attractions"),
        ("Icefall", "Outdoor/Natural Attractions"),
        ("Canyon", "Outdoor/Natural Attractions"),
        ("Lake", "Outdoor/Natural Attractions"),
        ("Landes", "Outdoor/Natural Attractions"),
        ("Stables", "Outdoor/Natural Attractions"),
        ("AlpinePasture", "Outdoor/Natural Attractions"),
        ("ChalkyLawn", "Outdoor/Natural Attractions"),
        ("Volcano", "Outdoor/Natural Attractions"),
        ("Plain", "Outdoor/Natural Attractions"),
        ("PigeonLoft", "Outdoor/Natural Attractions"),
        ("NaturalPark", "Outdoor/Natural Attractions"),
        ("Col", "Outdoor/Natural Attractions"),
        ("Mountain", "Outdoor/Natural Attractions"),
        ("Summit", "Outdoor/Natural Attractions"),
        ("Stone", "Outdoor/Natural Attractions"),
        ("IslandPeninsula", "Outdoor/Natural Attractions"),
        ("Beach", "Outdoor/Natural Attractions"),
        ("LevyOrDike", "Outdoor/Natural Attractions"),
        ("Wetland", "Outdoor/Natural Attractions"),
        ("Mine", "Outdoor/Natural Attractions"),
        ("Valley", "Outdoor/Natural Attractions"),
        ("Stream", "Outdoor/Natural Attractions"),
        ("RomanPath", "Outdoor/Natural Attractions"),
        ("Orchard", "Outdoor/Natural Attractions"),
        ("Hillsides", "Outdoor/Natural Attractions"),
        ("PicnicArea", "Outdoor/Natural Attractions"),
        ("UnderwaterRoute", "Outdoor/Natural Attractions"),
        ("NaturalHeritage", "Outdoor/Natural Attractions"),
        ("Waterfall", "Outdoor/Natural Attractions"),
        ("Canal", "Outdoor/Natural Attractions"),
        ("NaturalCuriosity", "Outdoor/Natural Attractions"),
        ("Cliff", "Outdoor/Natural Attractions"),
        ("LaunchingRamp", "Outdoor/Natural Attractions"),
        ("Dune", "Outdoor/Natural Attractions"),
        ("Causse", "Outdoor/Natural Attractions"),
        ("Synagogue", "Religious Centers"),
        ("ReligiousSite", "Religious Centers"),
        ("Calvary", "Religious Centers"),
        ("Mosque", "Religious Centers"),
        ("Temple", "Religious Centers"),
        ("Church", "Religious Centers"),
        ("Cloister", "Religious Centers"),
        ("Collegiate", "Religious Centers"),
        ("Cathedral", "Religious Centers"),
        ("CivilCemetery", "Religious Centers"),
        ("Basilica", "Religious Centers"),
        ("Abbey", "Religious Centers"),
        ("Commanderie", "Religious Centers"),
        ("Bishopric", "Religious Centers"),
        ("Chapel", "Religious Centers"),
        ("Monastery", "Religious Centers"),
        ("Convent", "Religious Centers"),
        ("BuddhistTemple", "Religious Centers"),
        ("ReligiousEvent", "Religious Centers"),
        ("CoveredMarket", "Shopping & Markets"),
        ("BricABrac", "Shopping & Markets"),
        ("Market", "Shopping & Markets"),
        ("LocalProductsShop", "Shopping & Markets"),
        ("Store", "Shopping & Markets"),
        ("CraftsmanShop", "Shopping & Markets"),
        ("GarageSale", "Shopping & Markets"),
        ("FitnessPath", "Sports & Recreation"),
        ("MiniGolf", "Sports & Recreation"),
        ("SportsEvent", "Sports & Recreation"),
        ("FreePractice", "Sports & Recreation"),
        ("BowlingAlley", "Sports & Recreation"),
        ("EquestrianCenter", "Sports & Recreation"),
        ("RacingCircuit", "Sports & Recreation"),
        ("SwimmingPool", "Sports & Recreation"),
        ("LeisureComplex", "Sports & Recreation"),
        ("Practice", "Sports & Recreation"),
        ("IceSkatingRink", "Sports & Recreation"),
        ("Racetrack", "Sports & Recreation"),
        ("Velodrome", "Sports & Recreation"),
        ("LeisureSportActivityProvider", "Sports & Recreation"),
        ("TennisComplex", "Sports & Recreation"),
        ("SquashCourt", "Sports & Recreation"),
        ("TrackRollerOrSkateBoard", "Sports & Recreation"),
        ("Course", "Sports & Recreation"),
        ("schema:SportsEvent", "Sports & Recreation"),
        ("Gymnasium", "Sports & Recreation"),
        ("SportsClub", "Sports & Recreation"),
        ("ClimbingWall", "Sports & Recreation"),
        ("AccompaniedPractice", "Sports & Recreation"),
        ("Trampoline", "Sports & Recreation"),
        ("SummerToboggan", "Sports & Recreation"),
        ("MultiActivity", "Sports & Recreation"),
        ("FirstPractice", "Sports & Recreation"),
        ("BoulesPitch", "Sports & Recreation"),
        ("CrossCountrySkiTrail", "Sports & Recreation"),
        ("ViaFerrata", "Sports & Recreation"),
        ("TobogganBobsleigh", "Sports & Recreation"),
        ("FitnessCenter", "Sports & Recreation"),
        ("SportsAndLeisurePlace", "Sports & Recreation"),
        ("schema:GolfCourse", "Sports & Recreation"),
        ("Stadium", "Sports & Recreation"),
        ("schema:StadiumOrArena", "Sports & Recreation"),
        ("GolfCourse", "Sports & Recreation"),
        ("PlaceOfInterest", "Tourist Attractions"),
        ("PointOfInterest", "Tourist Attractions"),
        ("Pier", "Transportation Hubs"),
        ("RailBike", "Transportation Hubs"),
        ("Marina", "Transportation Hubs"),
        ("Transport", "Transportation Hubs"),
        ("TouristTrain", "Transportation Hubs"),
        ("SightseeingBoat", "Transportation Hubs"),
        ("Bridge", "Transportation Hubs"),
        ("NauticalCentre", "Transportation Hubs"),
        ("Jetty", "Transportation Hubs"),
        ("RiverPort", "Transportation Hubs"),
        ("Seaport", "Transportation Hubs"),
    ]

    for row in mapping_list:
        yield {"data_gov_type": row[0], "new_type": row[1]}


if __name__ == "__main__":
    # configure the pipeline with your destination details
    pipeline = dlt.pipeline(
        pipeline_name="types_mapping",
        destination="snowflake",
        dataset_name="raw_types_mapping",
        progress=dlt.progress.tqdm(colour="yellow"),
    )

    # run the pipeline with your parameters
    info = pipeline.run(types_source())
    print(info)
